---
engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
    config: 'conf/pmd.xml'
  checkstyle:
    enabled: true
    channel: "beta"
ratings:
  paths:
    - "**.java"
exclude_paths: []
